name: Build Windows MSI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows-msi:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_Freeze
      
      - name: Build EXE
        # run: python build_windows.py bdist_msi
        run: cxfreeze -c main.py --target-dir dist
      
      - name: Upload EXE
        uses: actions/upload-artifact@v2
        with:
          name: myapp-exe
          path: dist/main.exe

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add dist/main.exe
          git commit -m "Add new EXE file"
          git push
          
    #   - name: Upload artifact
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: myapp-exe
    #       path: ./dist/

    #   - name: Commit changes
    #     uses: stefanzweifel/git-auto-commit-action@v4
    #     with:
    #       commit_message: Installer Update
    #       branch: main
    #       commit_options: '--no-verify --signoff'
    #       commit_author: Author <actions@github.com>
    #       status_options: '--untracked-files=no'
    #       skip_dirty_check: true