name: Build Windows MSI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows-msi:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_Freeze
      
      - name: Build EXE
        # run: python build_windows.py bdist_msi
        run: cxfreeze -c main.py --target-dir Installers
        # run: python build_windows.py bdist_msi
        # run: python build_windows.py bdist_exe
      
      # - name: Upload EXE
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: myapp-exe
      #     path: dist/main.exe

      # Make sure Github settings / permissions allow 
      # read / write access to Actions
      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add Installers/CarbonCheck.exe
          git commit -m "Add new EXE file"
          git push